### ISSUE TITLE
Remove getRandomString

### ISSUE THREAD

**Issue by moontear** [pnp/pnp#3]
Two issues with `common\util\getRandomString` (https://pnp.github.io/pnp/common/util.html):

1. It seems to be copied from Stackoverflow and attribution is not given: https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript
2. I can't think of any case we actually need a random string (besides testing)? If we don't generally need a random string within SharePoint, we shouldn't have a method in `/common` for it

I can submit a pull request removing all references to `getRandomString`, but I wanted to ask first whether I am missing a real world use case for it to be within the `common/util` lib.

**Comment by patrick-rodgers** [comment]
We can certainly add attribution. I don't actually recall if the method was taken from there or not, but is clearly very close. As you can see we have attribution for other methods so any omission wasn't intentional, but good you called us on it.

The getRandomString method is often used when dynamically building dom and other cases such as caching and is used by folks in their applications. We have left it in to help those folks from needing to include another library.
