### ISSUE TITLE
Include CamlJs in @pnp

### ISSUE THREAD

**Issue by phawrylak** [pnp/pnp#44]
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Question
Is it possible to incorporate [CamlJs](https://github.com/andrei-markeev/camljs) by @andrei-markeev into @pnp packages? This is really useful library and it would be great to have it maintained as @pnp package.

**Comment by patrick-rodgers** [comment]
Hi @phawrylak - circling back today on issues.

We have discussed this in the core team over the last week and we are not going to bring CamlJs into the pnp scope. This decision doesn't reflect anything about this particular library but is more thinking about long-term implications. Because we value your suggestion I wanted to outline our thinking in declining this request:

1. Adding packages without folks committed to maintaining them doesn't scale.
2. The package already exists, and folks who want to use it aren't blocked from doing so.
3. If we add this package would we then be committed to adding any package folks request? Would we then be responsible for maintaining all those packages (it would be implied)? And if not then we are now in a position of deciding what packages are "good enough to add to pnp" whatever that means. We don't think we should be in a position to bless packages. Folks should find and use the tools they want.

If there are clear gaps where no tools/libraries/samples exists, those are the areas where we can discuss adding a new package into the pnp scope or adding to an existing package.

**Next steps**

What I would suggest as a path forward is to reach out to @andrei-markeev and see if he is still interested in maintaining the library actively. If not, you could propose that you fork it and maintain a "copy" so that you can make the changes you need. We are happy to have you demo the library on a call and help drive knowledge.

Welcome your thoughts as well. Thanks!
